### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by SuperSandro2000** [maxwellainatchi/gnome-randr-rust#15]
It would be nice for downstream distros if releases where taggged.

**Comment by maxwellainatchi** [comment]
I haven't made any additional releases since the first, I didn't realize anyone was actually using it!

**Comment by maxwellainatchi** [comment]
I've created a release for the current commit on `main`, and if I continue to update this I'll make releases for new versions.

**Comment by SuperSandro2000** [comment]
Thanks!

**Comment by roberth** [comment]
Could you rename the tag to v0.1.1 to match the cargo file?

**Comment by maxwellainatchi** [comment]
Updated!
