### ISSUE TITLE
No List of Commands

### ISSUE THREAD

**Issue by InklingGirl** [maxwellainatchi/gnome-randr-rust#19]
`--help` yields:

```
gnome-randr 0.1.1
A program to query information about and manipulate displays on Gnome with Wayland.

Default command is `query`.

USAGE:
    gnome-randr [SUBCOMMAND]

FLAGS:
    -h, --help       
            Prints help information

    -V, --version    
            Prints version information


SUBCOMMANDS:
    help      Prints this message or the help of the given subcommand(s)
    modify    Modify allows you to alter the current display configuration.
    query     Query returns information about the current state of the monitors. This is the default subcommand.
```

Where are the rest of the commands? The traditional `xrandr` commands don't seem to be working either.

**Comment by FractalMachinist** [comment]
As a stop-gap, if you execute 'gnome-randr modify --help', it will show a help result for the modify subcommand.

**Comment by InklingGirl** [comment]
Ah, thank you @FractalMachinist. Also, there doesn't seem to be any subcommands to change monitor position, are there?

**Comment by FractalMachinist** [comment]
I've made a fork and pull request for basic repositioning. If you're interested, the main limitation is the CLI 'API' not letting you express commands for more than one monitor at a time. If that got added to the pull request, you'd probably get full positioning support. I hope that helps.

**Comment by maxwellainatchi** [comment]
@InklingGirl it's not supposed to use the same commands as xrandr. I'm not a huge fan of the xrandr interface, I wanted it to be a little clearer and more verbose. 

@FractalMachinist also intentional that you can only control one monitor at once, I wanted it to be unambiguous. If you want to control multiple monitors you can wrap this in a script.
