### ISSUE TITLE
[Question / Feature Request] Make changes persistent without having to allow via gnome-dialog

### ISSUE THREAD

**Issue by VeldoraTheDragon** [maxwellainatchi/gnome-randr-rust#22]
Hi there

I'm using gnome-randr in combination with a script, a service and a udev-rule, to automatically detect, when a display has been plugged in to, to set the resolution to the highest available of the external monitor.

Right now, it works pretty well, but when having multiple monitors attached and I want to set the resolution persistent, it proceeds and doesn't do any changes until I "accept" the changes.

Is there are way to make the changes persistent, without having to click on the gnome-asky-thingy to make my changes persistent? Somehow a method to bypass the dialog, yet the changes are made persistent.

Thank you for your answer.
Cheers
~ Veldora

**Comment by maxwellainatchi** [comment]
Hi! As far as I know it's not possible, since that mechanism is triggered via the DBUS API I'm using. However I'm not an expert, so there might be a way around it that I'm unfamiliar with.

**Comment by VeldoraTheDragon** [comment]
Hi @maxwellainatchi 
Just to let you know:
https://discourse.gnome.org/t/make-gnome-wayland-display-settings-persistent-without-asking/15575/3

According to Jonas Ådahl, it's not possible. So I'll close this issue on your behalf, since no further investigationis needed.
> Sorry, missed this part. No, there is no such way. You could probably implement avoiding it as an extension, but that’d mean it would do the same for Settings, for better or worse.
