### ISSUE TITLE
linker `cc` not found

### ISSUE THREAD

**Issue by cakePhone** [maxwellainatchi/gnome-randr-rust#25]
Here's the logs for my issue, the problem arises even when I clone the repo and try to build from source. I'm using NixOS 23.05 rn on Gnome.
```sh
$ cargo install gnome-randr
    Updating crates.io index
  Installing gnome-randr v0.1.1
   Compiling proc-macro2 v1.0.66
   Compiling version_check v0.9.4
   Compiling unicode-ident v1.0.11
   Compiling libc v0.2.147
   Compiling syn v1.0.109
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `proc-macro2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `libc` due to previous error
error: could not compile `syn` due to previous error
error: failed to compile `gnome-randr v0.1.1`, intermediate artifacts can be found at `/tmp/cargo-installCAy1PP`
```

**Comment by maxwellainatchi** [comment]
A quick google search says that you need to install gcc: https://stackoverflow.com/questions/58979682/linker-cc-not-found. I've never used NixOS but I'm guessing that it doesn't come with gcc out-of-the-box.

**Comment by cakePhone** [comment]
> A quick google search says that you need to install gcc: https://stackoverflow.com/questions/58979682/linker-cc-not-found. I've never used NixOS but I'm guessing that it doesn't come with gcc out-of-the-box. 

On NixOS, installing gcc doesn't fix it. This is due to it simply not being a "normal" package. I've started to use Nix flakes and shell to install stuffs. It usually works.
